#!/bin/sh -e
# script to run datconv
cp ../oa/ACPGF61.DAT ./
cp ../oa/PGBX3.DAT ./
cp ../ia/DATCONV.INF ./
./datconv
cp SYSSM.DAT ../oa/SYSSM.DAT
cp SYSSM.DAT ../oa/SYSC1.DAT
cp SYSSM.DAT ../oa/SYSC2.DAT
cp SYSSM.DAT ../oa/SYSFC.DAT
cp SYSSM.DAT ../oa/SYSRM.DAT
cp SYSSM.DAT ../oa/SYSSC.DAT

