      SUBROUTINE INB(X,AR1,AR2,AR3,AD,JL,NL,KL,CF,U,V)     
C     SRT TO CALCULATE AN INTERPOLATED VALUE OF A       
C     TABULAR FUNCTION BY NEWTON'S SECOND METHOD
C     AR1 IS THE ARRAY OF INDEPENDENT VARIABLE VALUES,EQUALLY SPACED    
C     AR2 IS THE ARRAY OF DEPENDENT VARIABLE VALUES     
C     AR3 IS THE ARRAY OF HORIZONTAL DIFFERENCES CALCULATED BY SRT DFB  
C     JL IS THE LENGTH OF ARRAYS AR1 AND AR2    
C     NL IS THE LENGTH OF ARRAY AR3     
C     KL IS THE ORDER OF DIFFERENCE TO USE FOR INTERPOLATION    
C     U IS THE FRACTIONAL DISTANCE OF THE ABSCISSA FROM THE LAST
C     PREVIOUS TABULAR VALUE,MEASURED IN UNITS OF ABSCISSA SPACING      
C     V IS THE INTERPOLATED OR EXTRAPOLATED VALUE RETURNED BY THIS SRT  
C       
C     USE NEAR THE END OF A TABLE       
C       
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION AR1(JL),AR2(JL),AR3(NL),CF(KL),AD(KL)
      H=AR1(2)-AR1(1)   
      DO 10 J=1,JL      
      U=(X-AR1(J))/H    
      IF (U.LT.0.D0) GO TO 3     
   10 CONTINUE  
    4 SB=1.D0
      CF(1)=U   
      V=0.D0   
      DO 5 K=2,KL       
      CF(K)=CF(K-1)*(U+SB)/(SB+1.D0)
      SB=SB+1.D0
    5 CONTINUE  
      DO 8 K=1,KL       
      KA=J+(KL-K)*JL    
      AD(K)=CF(KL-K+1)*AR3(KA)
    8 CONTINUE
      DO 9 K=1,KL-1
      IF (DABS(AD(K)).GT.(0.3D0*DABS(AD(K+1)))) THEN
         GO TO 9
      ELSE
         V=V+AD(K)
      END IF
    9 CONTINUE
    2 V=V+AR2(J)+AD(KL)
    7 RETURN    
    3 IF (J.GT.1) GO TO 4       
      CALL PMDSTOP      
      END       
