#!/bin/sh -e
# script to run SPT
cp ../ia/SPT.INF ./
cp ../oa/PGAX2.DAT ./
cp ../oa/PGBX6.DAT ./
cp ../oa/PGCX2.DAT ./
cp ../oa/PGBX2.DAT ./
cp ../ia/V436TOT.DAT ./
cp ../oa/PGDX3.DAT ./
cp ../ia/RFMG.DAT ./
cp ../ia/THLT.DAT ./
cp ../ia/PHAS.DAT ./
cp ../ia/SIGMA.DAT ./
cp ../ia/VNSE.DAT ./
cp ../ia/DPHS.DAT ./
cp ../ia/SDV.DAT ./
cp ../ia/INDATA.DAT ./
./spt
cp SPTDB.DAT ../oa/SPTDB.DAT
cp PGSX1.DAT ../oa/PGSX1.DAT
cp PGSX2.DAT ../oa/PGSX2.DAT
cp PGSX3.DAT ../oa/PGSX3.DAT
cp PGSX4.DAT ../oa/PGSX4.DAT
cp PGSX5.DAT ../oa/PGSX5.DAT
cp PGSX6.DAT ../oa/PGSX6.DAT
cp PGSX7.DAT ../oa/PGSX7.DAT
cp PGSX8.DAT ../oa/PGSX8.DAT
cp PGSX9.DAT ../oa/PGSX9.DAT
cp PGSX10.DAT ../oa/PGSX10.DAT
cp PGSX11.DAT ../oa/PGSX11.DAT
cp PGSX12.DAT ../oa/PGSX12.DAT
cp PGSX13.DAT ../oa/PGSX13.DAT
cp PGSX14.DAT ../oa/PGSX14.DAT
cp PGSX15.DAT ../oa/PGSX15.DAT
