#!/bin/sh
# script to run SPT
set -e
cp ../ia/SPT.INF ./
cp ../oa/PGAX2.DAT ./
cp ../oa/PGBX6.DAT ./
cp ../oa/PGCX2.DAT ./
cp ../oa/PGBX2.DAT ./
cp ../oa/VVTST3.MGS ./VVTST3.MGS
cp ../oa/PGDX3.DAT ./
cp ../ia/RFMG.DAT ./
cp ../ia/THLT.DAT ./
cp ../ia/PHAS.DAT ./
cp ../ia/SIGMA.DAT ./
cp ../ia/VNSE.DAT ./
cp ../ia/DPHS.DAT ./
./spt
cp SPTDB.DAT ../oa/
cp PGSX1.DAT ../oa/
cp PGSX2.DAT ../oa/
cp PGSX3.DAT ../oa/
cp PGSX4.DAT ../oa/
cp PGSX5.DAT ../oa/
cp PGSX6.DAT ../oa/
cp PGSX7.DAT ../oa/
cp PGSX8.DAT ../oa/
cp PGSX9.DAT ../oa/
cp PGSX10.DAT ../oa/
cp PGSX11.DAT ../oa/
cp PGSX12.DAT ../oa/
cp PGSX13.DAT ../oa/
cp PGSX14.DAT ../oa/
cp PGSX15.DAT ../oa/
cp SDV.DAT ../oa/
cp SPTDB.DAT ../oa/
cp INDATA.DAT ../oa/
