#!/bin/bash -e
set -e
# copy in input files for GRPD from ia/
cp ../ia/LINKV.DAT .
./grpd
# put output files back in oa/
cp GRPD.DAT ../oa/
#cp ../oa/GRPDDVI.DAT ../../plotfiles/DLDI.DAT
#cp ../oa/GRPDDVE.DAT ../../plotfiles/DLDECC.DAT
#cp ../oa/GRPDDVOM.DAT ../../plotfiles/DLDOM.DAT
set +e
