#!/bin/sh -e
# script to run acpgd
cp ../ia/ACPGD.INF ./
cp ../oa/PGAX2.DAT ./
cp ../oa/PGBX2.DAT ./
cp ../oa/PGBX3.DAT ./
cp ../oa/PGCX2.DAT ./
cp ../oa/PGCX3.DAT ./
cp ../oa/ACPGB2.DAT ./
cp ../oa/ACPGA2.DAT ./
cp ../oa/ACPGC2.DAT ./
cp ../oa/PGBX6.DAT ./
cp ../ia/CALPT.INF ./
cp ../ia/ACPGA.INF ./
./acpgd
cp ACPGD1.DAT ../oa/
cp ACPGD2.DAT ../oa/
cp ACPGD3.DAT ../oa/
cp ACPGD4.DAT ../oa/
