#!/bin/sh
# script to copy output files back to this directory
cp ~/binsyn/oa/CALPTO1.DAT ./
cp ~/binsyn/oa/PGAX1.DAT ./
cp ~/binsyn/oa/PGBX1.DAT ./
cp ~/binsyn/oa/PGCX1.DAT ./
cp ~/binsyn/oa/PGDX1.DAT ./
