#!/bin/sh
# script to copy necessary files to ../../ia/ and ~binsyn/oa
set -e
cp CALPT.INF ../../ia/
cp PGA.INF ../../ia/
cp PGB.INF ../../ia/
cp PGC.INF ../../ia/
cp PGD.INF ../../ia/
cp SPT.INF ../../ia/
cp LTCVA.INF ../../ia/
cp NOITA.DAT ../../oa/NOIT.DAT
cp NINCR.DAT ../../ia/
cp SUM1A.DAT ../../oa/SUM1.DAT
cp SUM1A.DAT ../../oa/SUM1.UPD
cp SUM2A.DAT ../../oa/SUM2.DAT
cp SUM2A.DAT ../../oa/SUM2.UPD
cp DIFCORR.INF ../../ia/
cp VVTST3.MGS ../../oa/
cp RFMG.DAT ../../ia/
cd ..
cd ..
cd calpt
./calptscr
cd ..
cd transf1
./transf1scr
cd ..
cd repl4
./repl4scr
cd ..
cd pga
./pgascr
cd ..
cd pgb
./pgbscr
cd ..
cd pgc
./pgcscr
cd ..
cd pgd
./pgdscr
cd ..
cd spt
./sptscr
cd ..
cd ltcva
./ltcvascr
cd ..
cd systems
cd Test5
cp ../../oa/CALPTO1.DAT ./
cp ../../oa/PGAX1.DAT ./
cp ../../oa/PGBX1.DAT ./
cp ../../oa/PGCX1.DAT ./
cp ../../oa/PGDX1.DAT ./
cp ../../oa/PGSX1.DAT ./
cp ../../oa/OBSLC1.DAT ./
cp ../../oa/THLC1.DAT ./
cp ../../oa/OBSLC2.DAT ./
cp ../../oa/THLC2.DAT ./
cp ../../oa/OBSLC3.DAT ./
cp ../../oa/THLC3.DAT ./
cp ../../oa/OBSLC4.DAT ./
cp ../../oa/THLC4.DAT ./
cp ../../oa/OBSLC5.DAT ./
cp ../../oa/THLC5.DAT ./
cp ../../oa/NOIT.DAT ./
cp ../../ia/NINCR.DAT ./
cp ../../oa/SUM1.DAT ./
cp ../../oa/SUM2.DAT ./
cp ../../oa/DIFCO1.DAT ./
