#!/bin/bash

# save where we are
WD=${PWD}

# go to binsyn top level
cd ../..

# run lgtsyn2
cd lgtsyn2/
./lgtsyn2

# go back to where we started.
cd ${WD}
cp ../../oa/CALPTO1.DAT ./
cp ../../oa/PGAX1.DAT ./
cp ../../oa/PGBX1.DAT ./
cp ../../oa/PGCX1.DAT ./
cp ../../oa/PGDX1.DAT ./
cp ../../oa/PGSX1.DAT ./
cp ../../oa/OBSLC1.DAT ./
cp ../../oa/THLC1.DAT ./
cp ../../oa/OBSLC2.DAT ./
cp ../../oa/THLC2.DAT ./
cp ../../oa/OBSLC3.DAT ./
cp ../../oa/THLC3.DAT ./
cp ../../oa/OBSLC4.DAT ./
cp ../../oa/THLC4.DAT ./
cp ../../oa/OBSLC5.DAT ./
cp ../../oa/THLC5.DAT ./
cp ../../oa/NOIT.DAT ./
cp ../../ia/NINCR.DAT ./
cp ../../oa/SUM1.DAT ./
cp ../../oa/SUM2.DAT ./
cp ../../oa/DIFCO1.DAT ./
