#!/bin/bash
# script to run ltres

set -e
cp ../ia/LTRES.INF ./
cp ../oa/PGSX5.DAT ./
cp ../ia/RFMG.DAT ./
./ltres
cp LTRES.DAT ../oa/
[ -f COL1.DAT ] && cp COL1.DAT ../oa/
[ -f COL2.DAT ] && cp COL2.DAT ../oa/
[ -f COL3.DAT ] && cp COL3.DAT ../oa/
[ -f COL4.DAT ] && cp COL4.DAT ../oa/
[ -f COL5.DAT ] && cp COL5.DAT ../oa/
