#!/bin/bash
set -e

cp ../oa/PGCX2.DAT .
cp ../oa/PEDCS.DAT .
cp ../oa/PGSX4.DAT .
./dvflcr
cp DLDI.DAT ../oa/
cp DLDECC.DAT ../oa/
cp DLDOM.DAT ../oa/
cp DLDPT1.DAT ../oa/
cp DLDPT2.DAT ../oa/
cp DLDQ.DAT ../oa/
cp DLDA1.DAT ../oa/
cp DLDA2.DAT ../oa/
cp DLDB1.DAT ../oa/
cp DLDB2.DAT ../oa/
cp DLDT1.DAT ../oa/
cp DLDT2.DAT ../oa/
cp DLDUC1.DAT ../oa/
cp DLDUC2.DAT ../oa/
cp DLDTZ1.DAT ../oa/
cp DLDTZ2.DAT ../oa/
cp DLDL31.DAT ../oa/
#
cp DLDI.DAT ../../plotfiles
cp DLDECC.DAT ../../plotfiles
cp DLDOM.DAT ../../plotfiles
cp DLDPT1.DAT ../../plotfiles
cp DLDPT2.DAT ../../plotfiles
cp DLDQ.DAT ../../plotfiles
cp DLDA1.DAT ../../plotfiles
cp DLDA2.DAT ../../plotfiles
cp DLDB1.DAT ../../plotfiles
cp DLDB2.DAT ../../plotfiles
cp DLDT1.DAT ../../plotfiles
cp DLDT2.DAT ../../plotfiles
cp DLDUC1.DAT ../../plotfiles
cp DLDUC2.DAT ../../plotfiles
cp DLDTZ1.DAT ../../plotfiles
cp DLDTZ2.DAT ../../plotfiles
cp DLDL31.DAT ../../plotfiles
