#!/bin/sh -e
# script to run pltdd
cp ../ia/PLTDD1.INF ./
cp ../ia/PLTDD2.INF ./
cp ../oa/PGAX2.DAT ./
cp ../oa/PGBX2.DAT ./
cp ../oa/PGBX3.DAT ./
cp ../ia/NSPOTS.DAT ./
cp ../ia/VLMDA.DAT ./
cp ../ia/VGMDA.DAT ./
cp ../ia/VBTDA.DAT ./
cp ../ia/VLMDB.DAT ./
cp ../ia/VGMDB.DAT ./
cp ../ia/VBTDB.DAT ./
cp ../ia/DLTAB.DAT ./
cp ../ia/RFMG.DAT ./
cp ../ia/PGA.INF ./
cp ../oa/ACPGA2.DAT ./
cp ../oa/ACPGB2.DAT ./
cp ../ia/ACPGC.INF ./
./pltdd
cp PLTDD1.DAT ../oa/
cp PLTDD2.DAT ../oa/
cp PLTDD3.DAT ../oa/
cp PLTDD4.DAT ../oa/
cp PLTDD5.DAT ../oa/
cp PLTDD6.DAT ../oa/
cp PLTDD7.DAT ../oa/
cp PLTDD8.DAT ../oa/
cp PLTDD9.DAT ../oa/
cp PLTDD10.DAT ../oa/
cp PLTDD11.DAT ../oa/
