      SUBROUTINE PDC(KYVA,NDV,KL,NRY,HARC,HARQ,HARR,HARD,HARE,HARF,
     $HARG,HARH,HARI,HARJ,HARK,HARL,HARM,HARN,HARO,HARP,KY1,KY2,KY3,
     $KY4,KY5,KY6,KY7,KY8,KY9,KY10,KY11,KY12,KY1A,KY2A,KY3A,KY4A,KY5A,
     $KY6A,KY7A,KY8A,KY9A,KY10A,KY11A,KY12A,XRY,ARRAA,ARRA,ARRBA,ARRB,
     $ARRCA,ARRC,ARRDA,ARRD,ARREA,ARRE,ARRFA,ARRF,ARRGA,ARRG,ARRHA,
     $ARRH,ARRIA,ARRI,ARRJA,ARRJ,ARRKA,ARRK,ARRLA,ARRL,ARRMA,ARRM,
     $ARRNA,ARRN,ARROA,ARRO,ARRPA,ARRP,
     $DLDI,DLDECC,DLDOM,DLDPT1,
     $DLDPT2,DLDQ,DLDA1,DLDA2,DLDB1,DLDB2,DLDT1,DLDT2,DLDUC1,DLDUC2,
     $DLDTZP,DLDTZS)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION VH(13),LV(13),VCLC(300)
      DIMENSION HARO(11),HARP(11),HARQ(11),HARR(11)
      DIMENSION HARC(11),HARD(11),HARE(11),HARF(11),HARG(11),
     $HARH(11),HARI(11),HARJ(11),HARK(11),HARL(11),HARM(11),HARN(11)
      DIMENSION PHR(300),DLDT1A(300),DLDT2A(300),DLDA1A(300),DLDA2A(300)
      DIMENSION DLDB1A(300),DLDB2A(300),DLDUC1A(300),DLDUC2A(300),
     $DLDPT1A(300),DLDPT2A(300),DLDQA(300),DLDIA(300),DLDTZPA(300),
     $DLDTZSA(300)
      DIMENSION XRY(11)
      DIMENSION ARRA(44),ARRB(44),ARRC(44),ARRD(44),
     $ARRE(44),ARRF(44),ARRG(44),ARRH(44),ARRI(44),
     $ARRJ(44),ARRK(44),ARRL(44),ARRM(44),ARRN(44),
     $ARRO(44),ARRP(44),ARRAA(44),ARRBA(44),ARRCA(44),ARRDA(44),
     $ARREA(44),ARRFA(44),ARRGA(44),ARRHA(44),ARRIA(44),ARRJA(44),
     $ARRKA(44),ARRLA(44),ARRMA(44),ARRNA(44),ARROA(44),ARRPA(44)
      COMMON/A/PI,TWOPI,HPI,CF,GVAL 
      COMMON/B/PH,DM,VL,WEMP,VH,LV
      COMMON/D/VI,POT1,POT2,QS,BA1,BA2,GD1,GD2,TP1,TP2,US1,US2,TZ1,TZ2,  
     $VL31,U,CNORM,AID,N,NSIT,NOIT,ISTEP    
      COMMON /E/ PHR,DLDT1A,DLDT2A,DLDA1A,DLDA2A,DLDB1A,DLDB2A,DLDUC1A,  
     $DLDUC2A,DLDPT1A,DLDPT2A,DLDQA,DLDIA,DLDTZPA,DLDTZSA,VCLC
      DATA TWPI/6.2831853071795864769D0/
C
      LG=4*NDV
      PHS=PH*TWPI
      IF (KYVA.EQ.KY1A) THEN
         KY2=0
         KY3=0
         KY4=0
         KY5=0
         KY6=0
         KY7=0
         KY8=0
         KY9=0
         KY10=0
         KY11=0
         KY12=0
      END IF
      IF (KYVA.EQ.KY2A) THEN
         KY1=0
         KY3=0
         KY4=0
         KY5=0
         KY6=0
         KY7=0
         KY8=0
         KY9=0
         KY10=0
         KY11=0
         KY12=0
      END IF
      IF (KYVA.EQ.KY3A) THEN
         KY1=0
         KY2=0
         KY4=0
         KY5=0
         KY6=0
         KY7=0
         KY8=0
         KY9=0
         KY10=0
         KY11=0
         KY12=0
      END IF
      IF (KYVA.EQ.KY4A) THEN
         KY1=0
         KY2=0
         KY3=0
         KY5=0
         KY6=0
         KY7=0
         KY8=0
         KY9=0
         KY10=0
         KY11=0
         KY12=0
      END IF
      IF (KYVA.EQ.KY5A) THEN
         KY1=0
         KY2=0
         KY3=0
         KY4=0
         KY6=0
         KY7=0
         KY8=0
         KY9=0
         KY10=0
         KY11=0
         KY12=0
      END IF
      IF (KYVA.EQ.KY6A) THEN
         KY1=0
         KY2=0
         KY3=0
         KY4=0
         KY5=0
         KY7=0
         KY8=0
         KY9=0
         KY10=0
         KY11=0
         KY12=0
      END IF
      IF (KYVA.EQ.KY7A) THEN
         KY1=0
         KY2=0
         KY3=0
         KY4=0
         KY5=0
         KY6=0
         KY8=0
         KY9=0
         KY10=0
         KY11=0
         KY12=0
      END IF
      IF (KYVA.EQ.KY8A) THEN
         KY1=0
         KY2=0
         KY3=0
         KY4=0
         KY5=0
         KY6=0
         KY7=0
         KY9=0
         KY10=0
         KY11=0
         KY12=0
      END IF
      IF (KYVA.EQ.KY9A) THEN
         KY1=0
         KY2=0
         KY3=0
         KY4=0
         KY5=0
         KY6=0
         KY7=0
         KY8=0
         KY10=0
         KY11=0
         KY12=0
      END IF
      IF (KYVA.EQ.KY10A) THEN
         KY1=0
         KY2=0
         KY3=0
         KY4=0
         KY5=0
         KY6=0
         KY7=0
         KY8=0
         KY9=0
         KY11=0
         KY12=0
      END IF
      IF (KYVA.EQ.KY11A) THEN
         KY1=0
         KY2=0
         KY3=0
         KY4=0
         KY5=0
         KY6=0
         KY7=0
         KY8=0
         KY9=0
         KY10=0
         KY12=0
      END IF
      IF (KYVA.EQ.KY12A) THEN
         KY1=0
         KY2=0
         KY3=0
         KY4=0
         KY5=0
         KY6=0
         KY7=0
         KY8=0
         KY9=0
         KY10=0
         KY11=0
      END IF
      IF ((KYVA.EQ.KY1A).AND.(KY1.GT.0)) GO TO 632          
      IF ((KYVA.EQ.KY2A).AND.(KY2.GT.0)) GO TO 632    
      IF ((KYVA.EQ.KY3A).AND.(KY3.GT.0)) GO TO 632          
      IF ((KYVA.EQ.KY4A).AND.(KY4.GT.0)) GO TO 632          
      IF ((KYVA.EQ.KY5A).AND.(KY5.GT.0)) GO TO 632          
      IF ((KYVA.EQ.KY6A).AND.(KY6.GT.0)) GO TO 632          
      IF ((KYVA.EQ.KY7A).AND.(KY7.GT.0)) GO TO 632          
      IF ((KYVA.EQ.KY8A).AND.(KY8.GT.0)) GO TO 632          
      IF ((KYVA.EQ.KY9A).AND.(KY9.GT.0)) GO TO 632          
      IF ((KYVA.EQ.KY10A).AND.(KY10.GT.0)) GO TO 632          
      IF ((KYVA.EQ.KY11A).AND.(KY11.GT.0)) GO TO 632          
      IF ((KYVA.EQ.KY12A).AND.(KY12.GT.0)) GO TO 632          
      CALL DFB(HARC,ARRAA,NRY,LG,KL)
      CALL DFF(HARC,ARRA ,NRY,LG,KL)
      CALL DFB(HARQ,ARRBA,NRY,LG,KL)
      CALL DFF(HARQ,ARRB ,NRY,LG,KL)
      CALL DFB(HARR,ARRCA,NRY,LG,KL)
      CALL DFF(HARR,ARRC ,NRY,LG,KL)
      CALL DFB(HARD,ARRDA,NRY,LG,KL)
      CALL DFF(HARD,ARRD ,NRY,LG,KL)
      CALL DFB(HARE,ARREA,NRY,LG,KL)
      CALL DFF(HARE,ARRE ,NRY,LG,KL)
      CALL DFB(HARF,ARRFA,NRY,LG,KL)
      CALL DFF(HARF,ARRF ,NRY,LG,KL)
      CALL DFB(HARG,ARRGA,NRY,LG,KL)
      CALL DFF(HARG,ARRG ,NRY,LG,KL)
      CALL DFB(HARH,ARRHA,NRY,LG,KL)
      CALL DFF(HARH,ARRH ,NRY,LG,KL)
      CALL DFB(HARI,ARRIA,NRY,LG,KL)
      CALL DFF(HARI,ARRI ,NRY,LG,KL)
      CALL DFB(HARJ,ARRJA,NRY,LG,KL)
      CALL DFF(HARJ,ARRJ ,NRY,LG,KL)
      CALL DFB(HARK,ARRKA,NRY,LG,KL)
      CALL DFF(HARK,ARRK ,NRY,LG,KL)
      CALL DFB(HARL,ARRLA,NRY,LG,KL)
      CALL DFF(HARL,ARRL ,NRY,LG,KL)
      CALL DFB(HARM,ARRMA,NRY,LG,KL)
      CALL DFF(HARM,ARRM ,NRY,LG,KL)
      CALL DFB(HARN,ARRNA,NRY,LG,KL)
      CALL DFF(HARN,ARRN ,NRY,LG,KL)
      CALL DFB(HARO,ARROA,NRY,LG,KL)
      CALL DFF(HARO,ARRO ,NRY,LG,KL)
      CALL DFB(HARP,ARRPA,NRY,LG,KL)
      CALL DFF(HARP,ARRP,NRY,LG,KL)
  632 CALL ITPL(PHS,XRY ,HARC,ARRAA ,ARRA ,NRY ,LG,CG,UV,DLDI)
      CALL ITPL(PHS,XRY ,HARQ,ARRBA ,ARRB ,NRY ,LG,CG,UV,DLDECC)
      CALL ITPL(PHS,XRY ,HARR,ARRCA, ARRC ,NRY ,LG,CG,UV,DLDOM)
      CALL ITPL(PHS,XRY ,HARD,ARRDA ,ARRD ,NRY,LG,CG,UV,DLDPT1)
      CALL ITPL(PHS,XRY ,HARE,ARREA ,ARRE ,NRY,LG,CG,UV,DLDPT2)
      CALL ITPL(PHS,XRY ,HARF,ARRFA ,ARRF ,NRY,LG,CG,UV,DLDQ)
      CALL ITPL(PHS,XRY ,HARG,ARRGA ,ARRG ,NRY ,LG,CG,UV,DLDA1)
      CALL ITPL(PHS,XRY ,HARH,ARRHA ,ARRH ,NRY ,LG,CG,UV,DLDA2)
      CALL ITPL(PHS,XRY ,HARI,ARRIA ,ARRI ,NRY ,LG,CG,UV,DLDB1)
      CALL ITPL(PHS,XRY ,HARJ,ARRJA ,ARRJ ,NRY ,LG,CG,UV,DLDB2)
      CALL ITPL(PHS,XRY ,HARK,ARRKA ,ARRK ,NRY ,LG,CG,UV,DLDT1)
      CALL ITPL(PHS,XRY ,HARL,ARRLA ,ARRL ,NRY ,LG,CG,UV,DLDT2)
      CALL ITPL(PHS,XRY ,HARM,ARRMA ,ARRM ,NRY ,LG,CG,UV,DLDUC1)
      CALL ITPL(PHS,XRY ,HARN,ARRNA ,ARRN ,NRY ,LG,CG,UV,DLDUC2)
      CALL ITPL(PHS,XRY ,HARO,ARROA ,ARRO ,NRY ,LG,CG,UV,DLDTZP)
      CALL ITPL(PHS,XRY ,HARP,ARRPA ,ARRP ,NRY ,LG,CG,UV,DLDTZS)
      IF (KYVA.EQ.KY1A) KY1=KY1+1        
      IF (KYVA.EQ.KY2A) KY2=KY2+1
      IF (KYVA.EQ.KY3A) KY3=KY3+1
      IF (KYVA.EQ.KY4A) KY4=KY4+1
      IF (KYVA.EQ.KY5A) KY5=KY5+1
      IF (KYVA.EQ.KY6A) KY6=KY6+1
      IF (KYVA.EQ.KY7A) KY7=KY7+1
      IF (KYVA.EQ.KY8A) KY8=KY8+1
      IF (KYVA.EQ.KY9A) KY9=KY9+1
      IF (KYVA.EQ.KY10A) KY10=KY10+1
      IF (KYVA.EQ.KY11A) KY11=KY11+1
      IF (KYVA.EQ.KY12A) KY12=KY12+1
      RETURN
      END 
