#!/bin/sh -e
# script to run PGD
cp ../ia/PGD.INF ./
cp ../oa/PGAX2.DAT ./
cp ../oa/PGBX2.DAT ./
cp ../oa/PGBX3.DAT ./
cp ../oa/PGBX6.DAT ./
cp ../oa/PGCX2.DAT ./
cp ../oa/PGCX3.DAT ./
./pgd
cp PGDX1.DAT ../oa/PGDX1.DAT
cp PGDX2.DAT ../oa/PGDX2.DAT
cp PGDX3.DAT ../oa/PGDX3.DAT
cp PGDX4.DAT ../oa/PGDX4.DAT
cp PGDX5.DAT ../oa/PGDX5.DAT
cp PGDX6.DAT ../oa/PGDX6.DAT
cp PGDX7.DAT ../oa/PGDX7.DAT
cp PGDX8.DAT ../oa/PGDX8.DAT
