#!/bin/sh -e
# script to run PGA
cp ../ia/PGA.INF ./
./pga
cp PGAX1.DAT ../oa/PGAX1.DAT
cp PGAX2.DAT ../oa/PGAX2.DAT
cp PGAX3.DAT ../oa/PGAX3.DAT
cp PGAX4.DAT ../oa/PGAX4.DAT
cp PGADB.DAT ../oa/PGADB.DAT
