#!/bin/sh
# script to copy necessary files to ../../ia/ and ~binsyn/oa
# this script produces light curves and corresponding plot files
set -e
echo "Have the following quantities been set?"
echo "RFMG.DAT"
echo "NOIT.DAT"
echo "NINCR.DAT"
echo "DIFCORR.INF"
echo "SUM1A.DAT"
echo "SUM2A.DAT"
echo "Have the assumed parameters been set in"
echo "CALPT.INF, PGA.INF, PGB.INF, and PGC.INF?"
echo "Has KCTRL been set to 2 in PGB.INF?"
cp CALPT.INF ../../ia/
cp PGA.INF ../../ia/
cp PGB.INF ../../ia/
cp PGC.INF ../../ia/
cp DIFCORR.INF ../../ia/
cp NINCR.DAT ../../ia/
cp RFMG.DAT ../../ia/
cp NOIT.DAT ../../oa/
cp SUM1.DAT ../../oa/
cp SUM2.DAT ../../oa/
cp THLT.DAT ../../ia/
cp DPHS.DAT ../../ia/
cp SIGMA.DAT ../../ia/
cp VNSE.DAT ../../ia/
cp LGTSYN3.INF ../../ia/
cp ACP6.DAT ../../ia/
cp DATCONV.INF ../../ia/
cd ../../lgtsyn3
./lgtsyn3scr
cd ../systems/Test9
cp ../../oa/SUM1.DAT ./
cp ../../oa/SUM2.DAT ./
cp ../../oa/NOIT.DAT ./
cp ../../oa/CALPTO1.DAT ./
cp ../../oa/PGAX1.DAT ./
cp ../../oa/PGBX1.DAT ./
cp ../../oa/PGCX1.DAT ./
cp ../../oa/PGDX1.DAT ./
cp ../../oa/PGSX1.DAT ./
cp ../../oa/OBSLC1.DAT ./
cp ../../oa/THLC1.DAT ./
cp ../../oa/OBSLC2.DAT ./
cp ../../oa/THLC2.DAT ./
cp ../../oa/OBSLC3.DAT ./
cp ../../oa/THLC3.DAT ./
cp ../../oa/OBSLC4.DAT ./
cp ../../oa/THLC4.DAT ./
cp ../../oa/OBSLC5.DAT ./
cp ../../oa/THLC5.DAT ./
cp ../../oa/DIFCO1.DAT ./
cp ../../ia/CALPT.INF ./
cp ../../ia/PGB.INF ./
cp ../../ia/PGC.INF ./
cp ../../ia/RFMG.DAT ./



