#!/bin/sh -e
# script to run pgb
cp ../ia/PGB.INF ./
cp ../ia/CALPT.INF ./
cp ../oa/PGAX2.DAT ./
cp ../ia/PGA.INF ./
cp ../ia/VVTSTBC6.DAT ./
./pgb
cp PGBX1.DAT ../oa/
cp PGBX2.DAT ../oa/
cp PGBX3.DAT ../oa/
cp PGBX4.DAT ../oa/
cp PGBX5.DAT ../oa/
cp PGBX6.DAT ../oa/
cp PGBDB.DAT ../oa/
cp PGBSHD.DAT ../oa/
