#!/bin/sh -e
# script to run ACPGF6
set -e
cp ../ia/ACP6.DAT ./
cp ../oa/RDVL3.DAT ./
cp ../oa/RDVL4.DAT ./
cp ../oa/RDVL5.DAT ./
cp ../oa/PGBX3.DAT ./
cp ../ia/LINKV.DAT ./
cp ../ia/ACPGA.INF ./
cp ../ia/PGA.INF ./
cp ../oa/PGDX5.DAT ./
#exit
./acpgf6
cp ACPGF61.DAT ../oa
cp ACPGF62.DAT ../oa
set +e
