#!/bin/sh
# script to run ACPGF6
cp ~/binsyn/ia/ACP6.DAT ./
cp ~/binsyn/oa/RDVL3.DAT ./
cp ~/binsyn/oa/RDVL4.DAT ./
cp ~/binsyn/oa/RDVL5.DAT ./
cp ~/binsyn/oa/PGBX3.DAT ./
cp ~/binsyn/ia/LINKV.DAT ./
cp ~/binsyn/ia/ACPGA.INF ./
cp ~/binsyn/ia/PGA.INF ./
./acpgf6
cp ACPGF61.DAT ~/binsyn/oa
cp ACPGF62.DAT ~/binsyn/oa
