#!/bin/sh
# script to copy necessary files to ~/binsyn/ia/ and ~binsyn/oa
cp CALPT.INF ~/binsyn/ia/
cp PGA.INF ~/binsyn/ia/
cp PGB.INF ~/binsyn/ia/
cp PGC.INF ~/binsyn/ia/
cp PGD.INF ~/binsyn/ia/
cd ..
cd ..
cd calpt
./calptscr
cd ..
cd transf1
./transf1scr
cd ..
cd repl4
./repl4scr
cd ..
cd pga
./pgascr
cd ..
cd pgb
./pgbscr
cd ..
cd pgc
./pgcscr
cd ..
cd pgd
./pgdscr
cd ..
cd systems
cd Test1
cp ~/binsyn/oa/CALPTO1.DAT ./
cp ~/binsyn/oa/PGAX1.DAT ./
cp ~/binsyn/oa/PGBX1.DAT ./
cp ~/binsyn/oa/PGCX1.DAT ./
cp ~/binsyn/oa/PGDX1.DAT ./
