#!/bin/sh
# script to copy necessary files to ../../ia/ and ~binsyn/oa
set -e
cp CALPT.INF ../../ia/
cp PGA.INF ../../ia/
cp PGB.INF ../../ia/
cp PGC.INF ../../ia/
cp PGD.INF ../../ia/
cp PLTB.INF ../../ia/
cp NSPOTS.DAT ../../ia/
cp VLMDA.DAT ../../ia/
cp VGMDA.DAT ../../ia/
cp VBTDA.DAT ../../ia/
cp VLMDB.DAT ../../ia/
cp VGMDB.DAT ../../ia/
cp VBTDB.DAT ../../ia/
cp RFMG.DAT ../../ia/
cp ACPGA.INF ../../ia/
cp ACPGB.INF ../../ia/
cp ACPGC.INF ../../ia/
cp ACPGD.INF ../../ia/
cp RDVEL2.INF ../../ia/
cp ACP6.DAT ../../ia/
cp DATCONV.INF ../../ia/
cp t4000g40nr08.7 ../../acpgf6/
cp t5000g40nr08.7 ../../acpgf6/
cp t6000g40nrw08.7 ../../acpgf6/
cp t6500g40nrw08.7 ../../acpgf6/
cd ..
cd ..
cd calpt
./calptscr
cd ..
cd transf1
./transf1scr
cd ..
cd repl4
./repl4scr
cd ..
cd pga
./pgascr
cd ..
cd pgb
./pgbscr
cd ..
cd pgc
./pgcscr
cd ..
cd pgd
./pgdscr
cd ..
cd pltb
./pltbscr
cd ..
cd acpga
./acpgascr
cd ..
cd acpgb
./acpgbscr
cd ..
cd acpgc
./acpgcscr
cd ..
cd acpgd
./acpgdscr
cd ..
cd rdvel2
./rdvel2scr
cd ..
cd acpgf6
./acpgf6scr
rm t4000g40nr08.7
rm t5000g40nr08.7
rm t6000g40nrw08.7
rm t6500g40nrw08.7
cd ..
cd datconv
./datconvscr
cd ..
cd systems
cd Test4
cp ../../oa/CALPTO1.DAT ./
cp ../../oa/PGAX1.DAT ./
cp ../../oa/PGBX1.DAT ./
cp ../../oa/PGCX1.DAT ./
cp ../../oa/PGDX1.DAT ./
cp ../../oa/ACPGA1.DAT ./
cp ../../oa/ACPGB1.DAT ./
cp ../../oa/ACPGC1.DAT ./
cp ../../oa/ACPGD1.DAT ./
cp ../../oa/ACPGF61.DAT ./
cp ../../oa/SYSSM.DAT ./
cp ../../oa/SYSC1.DAT ./
cp ../../oa/SYSC2.DAT ./
cp ../../oa/SYSSM.DAT ../../../plotfiles/
cp ../../oa/SYSC1.DAT ../../../plotfiles/
cp ../../oa/SYSC2.DAT ../../../plotfiles/

