#!/bin/sh
# script to copy necessary files to ../../ia/ and ~binsyn/oa
# this script produces light curves and corresponding plot files
set -e
echo "Have the following quantities been set?"
echo "RFMG.DAT"
echo "NOIT.DAT"
echo "NINCR.DAT"
echo "DIFCORR.INF"
echo "SUM1A.DAT"
echo "SUM2A.DAT"
echo "Have the assumed parameters been set in"
echo "CALPT.INF, PGB.INF, and PGC.INF?"
echo "Has KCTRL been set to 2 in PGB.INF?"
cp CALPT.INF ../../ia/
cp PGB.INF ../../ia/
cp PGC.INF ../../ia/
cp ACPGA.INF ../../ia/
cp ACPGB.INF ../../ia/
cp ACPGC.INF ../../ia/
cp DIFCORR.INF ../../ia/
cp NINCR.DAT ../../ia/
cp RFMG5.DAT RFMG.DAT
cp RFMG.DAT ../../ia/
cp NOIT.DAT ../../oa/
cp SUM1.DAT ../../oa/
cp SUM2.DAT ../../oa/
cp THLT.DAT ../../ia/
cp PHAS.DAT ../../ia/
cp DPHS.DAT ../../ia/
cp SIGMA.DAT ../../ia/
cp VNSE.DAT ../../ia/
cp LGTSYN3.INF ../../ia/
cp SYNPHOT.INF ../../ia/
cp ACP6.DAT ../../ia/
cp SYNPHOT.ADD ../../ia/
echo "Have acpgf6 and datconv been set properly?"
cd ../../lgtsyn3
./lgtsyn3scr
cd ../oa/
cp SUM1.DAT ~/binsyn/systems/Test8
cp SUM2.DAT ~/binsyn/systems/Test8
cp NOIT.DAT ~/binsyn/systems/Test8
cp DIFCO1.DAT ~/binsyn/systems/Test8
cp LGTSYN3TM.DAT ~/binsyn/systems/Test8
cd ../ia/
cp CALPT.INF ~/binsyn/systems/Test8
cp PGB.INF ~/binsyn/systems/Test8
cp PGC.INF ~/binsyn/systems/Test8
cp RFMG5.DAT RFMG.DAT
cp RFMG.DAT ~/binsyn/systems/Test8
set +e


