#!/bin/sh
# script to copy necessary files to ../../ia/ and ~binsyn/oa
# this script produces light curves and corresponding plot files
set -e
cp CALPT.INF ../../ia/
cp PGA.INF ../../ia/
cp PGB.INF ../../ia/
cp PGC.INF ../../ia/
cp PGD.INF ../../ia/
cp NSPOTS.DAT ../../ia/
cp VLMDA.DAT ../../ia/
cp VGMDA.DAT ../../ia/
cp VBTDA.DAT ../../ia/
cp VLMDB.DAT ../../ia/
cp VGMDB.DAT ../../ia/
cp VBTDB.DAT ../../ia/
cp SPT.INF ../../ia/
cp LTCVA.INF ../../ia/
cp RFMG.DAT ../../ia/
cd ../../
cd calpt
./calptscr
cd ..
cd transf1
./transf1scr
cd ..
cd repl4
./repl4scr
cd ..
cd pga
./pgascr
cd ..
cd pgb
./pgbscr
cd ..
cd pltb
./pltbscr
cd ..
cd pgc
./pgcscr
cd ..
cd pgd
./pgdscr
#exit
cd ..
cd spt
./sptscr
cd ..
cd ltcva
./ltcvascr
cd ..
cd ltres
./ltresscr
cd ..
cd oa
cp PGBX3.DAT PGBX3SV.DAT
cd ..
cd fxpgbx3sv
# set KCTRL=2 in PGBX3SV.DAT
./fxpgbx3svscr
cd ../oa
cp PGDX3.DAT PGDX3SV.DAT
cp PGBX6.DAT PGBX6SV.DAT
cd ../systems/Test8
cp ../../oa/CALPTO1.DAT ./
cp ../../oa/PGAX1.DAT ./
cp ../../oa/PGBX1.DAT ./
cp ../../oa/PGCX1.DAT ./
cp ../../oa/PGDX1.DAT ./
cp ../../oa/PGSX1.DAT ./
cp ../../oa/OBSLC1.DAT ./
cp ../../oa/THLC1.DAT ./
cp ../../oa/OBSLC2.DAT ./
cp ../../oa/THLC2.DAT ./
cp ../../oa/OBSLC3.DAT ./
cp ../../oa/THLC3.DAT ./
cp ../../oa/OBSLC4.DAT ./
cp ../../oa/THLC4.DAT ./
cp ../../oa/OBSLC5.DAT ./
cp ../../oa/THLC5.DAT ./
set +e



