#!/bin/sh
# script to copy necessary files to ../../ia/ and ~binsyn/oa
# this script produces light curves and corresponding plot files
set -e
echo "Have the following quantities been set?"
echo "RFMG.DAT"
echo "NOIT.DAT"
echo "NINCR.DAT"
echo "DIFCORR.INF"
echo "SUM1A.DAT"
echo "SUM2A.DAT"
echo "Have the assumed parameters been set in"
echo "CALPT.INF, PGB.INF, and PGC.INF?"
echo "Has KCTRL been set to 2 in PGB.INF?"
cp CALPT.INF ../../ia/
cp PGB.INF ../../ia/
cp PGC.INF ../../ia/
cp ACPGA.INF ../../ia/
cp ACPGB.INF ../../ia/
cp ACPGC.INF ../../ia/
cp DIFCORR.INF ../../ia/
cp NINCR.DAT ../../ia/
cp RFMG5.DAT RFMG.DAT
cp RFMG.DAT ../../ia/
cp NOIT.DAT ../../oa/
cp SUM1.DAT ../../oa/
cp SUM2.DAT ../../oa/
cp THLT.DAT ../../ia/
cp PHAS.DAT ../../ia/
cp DPHS.DAT ../../ia/
cp SIGMA.DAT ../../ia/
cp VNSE.DAT ../../ia/
cp LGTSYN3.INF ../../ia/
cp SYNPHOT.INF ../../ia/
cp ACP6.DAT ../../ia/
cp SYNPHOT.ADD ../../ia/
cp T4000g40kur.17 ../../acpgf6/
cp T5000g40kur.17 ../../acpgf6/
cp T6000g40kur.17 ../../acpgf6/
cp T6500g40kur.17 ../../acpgf6/
cp T6750g40kur.17 ../../acpgf6/
cp T7000g40kur.17 ../../acpgf6/
cp T8000g40kur.17 ../../acpgf6/
cp T9000g40kur.17 ../../acpgf6/
cp T9500g40kur.17 ../../acpgf6/
cp T9750g40kur.17 ../../acpgf6/
cp T10000g40kur.17 ../../acpgf6/
cp T11000g40kur.17 ../../acpgf6/
cp T12000g40kur.17 ../../acpgf6/
cp T4000g45kur.17 ../../acpgf6/
cp T5000g45kur.17 ../../acpgf6/
cp T6000g45kur.17 ../../acpgf6/
cp T6500g45kur.17 ../../acpgf6/
cp T6750g45kur.17 ../../acpgf6/
cp T7000g45kur.17 ../../acpgf6/
cp T8000g45kur.17 ../../acpgf6/
cp T9000g45kur.17 ../../acpgf6/
cp T9500g45kur.17 ../../acpgf6/
cp T9750g45kur.17 ../../acpgf6/
cp T10000g45kur.17 ../../acpgf6/
cp T11000g45kur.17 ../../acpgf6/
cp T12000g45kur.17 ../../acpgf6/
echo "Have acpgf6 and datconv been set properly?"
cd ../../lgtsyn3
./lgtsyn3scr
cd ../systems/Test8
cp ../../oa/SUM1.DAT ./
cp ../../oa/SUM2.DAT ./
cp ../../oa/NOIT.DAT ./
cp ../../oa/DIFCO1.DAT ./
cp ../../oa/LGTSYN3TM.DAT ./
cp ../../ia/CALPT.INF ./
cp ../../ia/PGB.INF ./
cp ../../ia/PGC.INF ./
cp ../../ia/RFMG.DAT ./
set +e

