#!/bin/sh
# script to copy necessary files to ../../ia/ and ~binsyn/oa
# this script produces light curves and corresponding plot files
set -e
echo "Have the following quantities been set?"
echo "RFMG.DAT"
echo "NOIT.DAT"
echo "NINCR.DAT"
echo "DIFCORR.INF"
echo "SUM1A.DAT"
echo "SUM2A.DAT"
echo "Have the assumed parameters been set in"
echo "CALPT.INF, PGB.INF, and PGC.INF?"
echo "Has KCTRL been set to 2 in PGB.INF?"
cp CALPT.INF ../../ia/
cp PGA.INF ../../ia/
cp PGB.INF ../../ia/
cp PGC.INF ../../ia/
cp NSPOTS.DAT ../../ia/
cp VLMDA.DAT ../../ia/
cp VGMDA.DAT ../../ia/
cp VBTDA.DAT ../../ia/
cp VLMDB.DAT ../../ia/
cp VGMDB.DAT ../../ia/
cp VBTDB.DAT ../../ia/
cp DLTAA.DAT ../../ia/
cp DLTAB.DAT ../../ia/
cp DIFCORR.INF ../../ia/
cp NINCR.DAT ../../ia/
cp RFMG5.DAT RFMG.DAT
cp RFMG.DAT ../../ia/
cp NOIT.DAT ../../oa/
cp SUM1.DAT ../../oa/
cp SUM2.DAT ../../oa/
cp THLT.DAT ../../ia/
cp DPHS.DAT ../../ia/
cp PHAS.DAT ../../ia/
cp SIGMA.DAT ../../ia/
cp VNSE.DAT ../../ia/
cp LGTSYN2.INF ../../ia/
cd ../../lgtsyn2
./lgtsyn2scr
cd ../systems/Test8
cp ../../oa/SUM1.DAT ./
cp ../../oa/SUM2.DAT ./
cp ../../oa/NOIT.DAT ./
cp ../../oa/DIFCO1.DAT ./
cp ../../oa/LGTSYN2TM.DAT ./
cp ../../ia/CALPT.INF ./
cp ../../ia/PGB.INF ./
cp ../../ia/PGC.INF ./
cp ../../ia/RFMG.DAT ./
set +e


