#!/bin/sh
# script to copy necessary files to ../../ia/ and ~binsyn/oa
set -e
cp CALPT.INF ~/binsyn/ia/
cp PGA.INF ~/binsyn/ia/
cp PGB.INF ~/binsyn/ia/
cp PGC.INF ~/binsyn/ia/
cp PGD.INF ~/binsyn/ia/
cp PLTB.INF ~/binsyn/ia/
cp NSPOTS.DAT ~/binsyn/ia/
cp VLMDA.DAT ~/binsyn/ia/
cp VGMDA.DAT ~/binsyn/ia/
cp VBTDA.DAT ~/binsyn/ia/
cp VLMDB.DAT ~/binsyn/ia/
cp VGMDB.DAT ~/binsyn/ia/
cp VBTDB.DAT ~/binsyn/ia/
cp RFMG.DAT ~/binsyn/ia/
cp ACPGA.INF ~/binsyn/ia/
cp ACPGB.INF ~/binsyn/ia/
cp ACPGC.INF ~/binsyn/ia/
cp ACPGD.INF ~/binsyn/ia/
cp RDVEL2.INF ~/binsyn/ia/
cp ACP6.DAT ~/binsyn/ia/
cp DATCONV.INF ~/binsyn/ia/
cp ./r4500nl08.7 ~/binsyn/acpgf6/
cp ./r4000nl08.7 ~/binsyn/acpgf6/
cp ./r3500nl08.7 ~/binsyn/acpgf6/
cp ./r3000nl08.7 ~/binsyn/acpgf6/
cp ./r2600nll08.7 ~/binsyn/acpgf6/
cp ./r2200nll08.7 ~/binsyn/acpgf6/
cp ./r2000nll08.7 ~/binsyn/acpgf6/
cp ./r1800nll08.7 ~/binsyn/acpgf6/
cp ./r1600nll08.7 ~/binsyn/acpgf6/
cp ./r1400nll08.7 ~/binsyn/acpgf6/
cp ./r1200nll08.7 ~/binsyn/acpgf6/
cp ./r1000nll08.7 ~/binsyn/acpgf6/
cp ./r0900nll08.7 ~/binsyn/acpgf6/
cp ./r0800nll08.7 ~/binsyn/acpgf6/
cp ./r0700nll08.7 ~/binsyn/acpgf6/
cp ./r0600nll08.7 ~/binsyn/acpgf6/
cp ./r0500nll08.7 ~/binsyn/acpgf6/
cp ./r0400nll08.7 ~/binsyn/acpgf6/
cp ./r0300nll08.7 ~/binsyn/acpgf6/
cp ./r0200nll08.7 ~/binsyn/acpgf6/
cp ./r0136nll08.7 ~/binsyn/acpgf6/
cp t50g80nll08.7 ~/binsyn/acpgf6/
cp t3500g40nrw08.7 ~/binsyn/acpgf6/
cd ../../
cd calpt
./calptscr
cd ..
cd transf1
./transf1scr
cd ..
cd repl4
./repl4scr
cd ..
cd pga
./pgascr
cd ..
cd pgb
./pgbscr
cd ..
cd pgc
./pgcscr
cd ..
cd pgd
./pgdscr
cd ..
cd pltb
./pltbscr
cd ..
cd acpga
./acpgascr
cd ..
cd acpgb
./acpgbscr
cd ..
cd acpgc
./acpgcscr
cd ..
cd acpgd
./acpgdscr
cd ..
cd pltdd
./pltddscr
cd ..
cd horzplta
./horzpltascr
cd ..
cd rdvel2
./rdvel2scr
cd ..
cd acpgf6
./acpgf6scr
# must copy following files to ~/binsyn/datconv
cp ../oa/ACPGF61.DAT ~/binsyn/datconv/
cp ../oa/PGBX3.DAT ~/binsyn/datconv/
cd ..
cd datconv
./datconvscr
cd ..
cd systems/Test7
cp ~/binsyn/oa/CALPTO1.DAT ./
cp ~/binsyn/oa/PGAX1.DAT ./
cp ~/binsyn/oa/PGBX1.DAT ./
cp ~/binsyn/oa/PGCX1.DAT ./
cp ~/binsyn/oa/PGDX1.DAT ./
cp ~/binsyn/oa/ACPGA1.DAT ./
cp ~/binsyn/oa/ACPGB1.DAT ./
cp ~/binsyn/oa/ACPGC1.DAT ./
cp ~/binsyn/oa/ACPGD1.DAT ./
cp ~/binsyn/oa/ACPGF61.DAT ./
cp ~/binsyn/oa/SYSSM.DAT ./
cp ~/binsyn/oa/SYSC1.DAT ./
cp ~/binsyn/oa/SYSC2.DAT ./
cp ~/binsyn/oa/SYSSM.DAT ~/plotfiles/
cp ~/binsyn/oa/SYSC1.DAT ~/plotfiles/
cp ~/binsyn/oa/SYSC2.DAT ~/plotfiles/
cp ~/binsyn/oa/SYSFC.DAT ~/plotfiles/
cp ~/binsyn/oa/SYSRM.DAT ~/plotfiles/
cp ~/binsyn/oa/PLTDD2.DAT ~/plotfiles/
cp ~/binsyn/oa/PLTDD8.DAT ~/plotfiles/
cp ~/binsyn/oa/PLTB6.DAT ~/plotfiles/
cp ~/binsyn/oa/PLTB7.DAT ~/plotfiles/
cp ~/binsyn/oa/PLTB8.DAT ~/plotfiles/
cp ~/binsyn/oa/PLTB9.DAT ~/plotfiles/



