#!/bin/sh
# script to run pltb
cp ~/binsyn/ia/PLTB.INF ./
cp ~/binsyn/oa/PGAX2.DAT ./
cp ~/binsyn/oa/PGBX2.DAT ./
cp ~/binsyn/oa/PGBX6.DAT ./
cp ~/binsyn/ia/NSPOTS.DAT ./
cp ~/binsyn/ia/VLMDA.DAT ./
cp ~/binsyn/ia/VGMDA.DAT ./
cp ~/binsyn/ia/VBTDA.DAT ./
cp ~/binsyn/ia/VLMDB.DAT ./
cp ~/binsyn/ia/VGMDB.DAT ./
cp ~/binsyn/ia/VBTDB.DAT ./
cp ~/binsyn/ia/RFMG.DAT ./
./pltb
cp PLTB.DAT ~/binsyn/oa/
cp PLTB2.DAT ~/binsyn/oa/
cp PLTB3.DAT ~/binsyn/oa/
cp PLTB4.DAT ~/binsyn/oa/
cp PLTB5.DAT ~/binsyn/oa/
cp PLTB6.DAT ~/binsyn/oa/
cp PLTB7.DAT ~/binsyn/oa/
cp PLTB8.DAT ~/binsyn/oa/
cp PLTB9.DAT ~/binsyn/oa/
cp PLTB10.DAT ~/binsyn/oa/
cp PLTB11.DAT ~/binsyn/oa/
cp PLTB12.DAT ~/binsyn/oa/
cp PLTB13.DAT ~/binsyn/oa/
cp PLTB14.DAT ~/binsyn/oa/
cp PLTB15.DAT ~/binsyn/oa/
cp PLTB16.DAT ~/binsyn/oa/
cp PLTB17.DAT ~/binsyn/oa/
cp PLTB18.DAT ~/binsyn/oa/
cp PLTB19.DAT ~/binsyn/oa/
cp PLTB20.DAT ~/binsyn/oa/
cp PLTB21.DAT ~/binsyn/oa/
cp PLTB22.DAT ~/binsyn/oa/
cp PLTB23.DAT ~/binsyn/oa/
