#!/bin/sh -e
# script to run rdvel
cp ../ia/RDVEL2.INF ./
cp ../oa/PGAX2.DAT ./
cp ../oa/PGBX2.DAT ./
cp ../oa/PGBX3.DAT ./
cp ../ia/CALPT.INF ./
cp ../oa/PGCX2.DAT ./
cp ../oa/ACPGA2.DAT ./
cp ../oa/ACPGB2.DAT ./
cp ../oa/ACPGC2.DAT ./
cp ../oa/PGDX4.DAT ./
cp ../oa/PGDX7.DAT ./
./rdvel2
cp RDVL1.DAT ../oa/
cp RDVL2.DAT ../oa/
cp RDVL3.DAT ../oa/
cp RDVL4.DAT ../oa/
cp RDVL5.DAT ../oa/
cp RDVL6.DAT ../oa/
cp RDVL7.DAT ../oa/
cp RDVL8.DAT ../oa/
cp RDVL9.DAT ../oa/

