#!/bin/sh -e
# script to run PGC
cp ../ia/PGC.INF ./
cp ../ia/PGCA.INF ./
cp ../ia/NSPOTS.DAT ./
cp ../ia/VLMDA.DAT ./
cp ../ia/VGMDA.DAT ./
cp ../ia/VBTDA.DAT ./
cp ../ia/DLTAA.DAT ./
cp ../ia/VLMDB.DAT ./
cp ../ia/VGMDB.DAT ./
cp ../ia/VBTDB.DAT ./
cp ../ia/DLTAB.DAT ./
cp ../rfda/LMDK2.DAT ../ia/
cp ../ia/LMDK2.DAT ./
cp ../rfda/MDATDT2.DAT ../ia/
cp ../ia/MDATDT2.DAT ./
cp ../rfda/WVLST2.DAT ../ia/
cp ../ia/WVLST2.DAT ./
cp ../rfda/TMPLST2.DAT ../ia/
cp ../ia/TMPLST2.DAT ./
cp ../rfda/GVLST2.DAT ../ia/
cp ../ia/GVLST2.DAT ./
cp ../oa/PGAX2.DAT ./
cp ../oa/PGBX2.DAT ./
./pgc
cp PGCX1.DAT ../oa/PGCX1.DAT
cp PGCX2.DAT ../oa/PGCX2.DAT
cp PGCX3.DAT ../oa/PGCX3.DAT
cp PGCX4.DAT ../oa/PGCX4.DAT
cp PGCDBG.DAT ../oa/PGCDBG.DAT
