#!/bin/sh
# script to copy necessary files to ../../ia/ and ~binsyn/oa
set -e
cp CALPT.INF ../../ia/
cp PGA.INF ../../ia/
cp PGB.INF ../../ia/
cp PGC.INF ../../ia/
cp PGD.INF ../../ia/
cp NSPOTS.DAT ../../ia/
cp VLMDA.DAT ../../ia/
cp VGMDA.DAT ../../ia/
cp VBTDA.DAT ../../ia/
cp VLMDB.DAT ../../ia/
cp VGMDB.DAT ../../ia/
cp VBTDB.DAT ../../ia/
cp DLTAA.DAT ../../ia/
cp DLTAB.DAT ../../ia/
cp SPT.INF ../../ia/
cp RFMG.DAT ../../ia/
cp THLT.DAT ../../ia/
cp PHAS.DAT ../../ia/
cp SIGMA.DAT ../../ia/
cp VNSE.DAT ../../ia/
cp DPHS.DAT ../../ia/
cp LTCVA.INF ../../ia/
cp LTCVA.ILS ../../ltcva/
cp Test2.MGS ../../ltcva/
cp VVTST3.MGS ../../oa/VVTST3.MGS
cd ..
cd ..
cd calpt
./calptscr
cd ..
cd transf1
./transf1scr
cd ..
cd repl4
./repl4scr
cd ..
cd pga
./pgascr
cd ..
cd pgb
./pgbscr
cd ..
cd pgc
./pgcscr
cd ..
cd pgd
./pgdscr
cd ..
cd spt
./sptscr
cd ..
cd ltcva
./ltcvascr
cp ../oa/CALPTO1.DAT ../systems/Test2/
cp ../oa/PGAX1.DAT ../systems/Test2/
cp ../oa/PGBX1.DAT ../systems/Test2/
cp ../oa/PGCX1.DAT ../systems/Test2/
cp ../oa/PGDX1.DAT ../systems/Test2/
cp ../oa/PGSX1.DAT ../systems/Test2/
cp ../oa/OBSLC1.DAT ../systems/Test2/
cp ../oa/THLC1.DAT ../systems/Test2/
cp ../systems/Test2/LTCVA.ILS.DEF ./LTCVA.ILS
set +e

