C     Physical constants
C
      DATA SNRAD/6.9599D10/        !Sun radius,cgs
      DATA SOL/6.27D10/            !Solar surface flux,cgs.
      DATA SOLMS/1.9891D33/        !Solar mass, cgs.
      DATA GRAV/6.6704D-8/         !Gravity const.
      DATA YRSEC/3.1556926D7/      !Length of year, in sec.
      DATA COEF/1.4044D-4/         !(3G/(8*PI*SIGMA))
      DATA SGMA/5.6696D-5/         !Radiation constant
      DATA BOLTZ/1.380626D-16/     !Boltzmann constant
	DATA VLIGHT/2.99792501D10/   !Velocity of light
	DATA AMUMS/1.67352D-24/      !Mass of one atomic mass unit
	DATA SGTM/6.652D-25/         !Thomson cross section
