#!/bin/sh -e
# script to run acpgb
cp ../ia/ACPGB.INF ./
cp ../ia/ACPGA.INF ./
cp ../oa/ACPGA2.DAT ./
cp ../oa/PLTB3.OUT ./
cp ../oa/PGAX2.DAT ./
cp ../oa/PGBX2.DAT ./
cp ../oa/PGBX3.DAT ./
cp ../ia/LINKV.DAT ./
./acpgb
cp ACPGB1.DAT ../oa/
cp ACPGB2.DAT ../oa/
cp ACPGB3.DAT ../oa/
cp ACPGB4.DAT ../oa/
cp ACPGB5.DAT ../oa/
cp ACPGB6.DAT ../oa/
cp ACPGB7.DAT ../oa/
cp ACPGB8.DAT ../oa/

