#!/bin/sh
# script to run LTCVA
cp ~/binsyn/ia/RFMG.DAT ./
cp ~/binsyn/ia/DPHS.DAT ./
cp ~/binsyn/oa/PGSX8.DAT ./
cp ~/binsyn/oa/LTCVA.DAT ./
cp ~/binsyn/oa/OBSLC1.DAT ./
cp ~/binsyn/oa/THLC1.DAT ./
cp ~/binsyn/oa/OBSLC2.DAT ./
cp ~/binsyn/oa/THLC2.DAT ./
cp ~/binsyn/oa/OBSLC2.DAT ./
cp ~/binsyn/oa/THLC3.DAT ./
cp ~/binsyn/oa/OBSLC4.DAT ./
cp ~/binsyn/oa/THLC4.DAT ./
cp ~/binsyn/oa/OBSLC5.DAT ./
cp ~/binsyn/oa/THLC5.DAT ./
./ltcva
cp THLC1.DAT ~/binsyn/oa/
cp OBSLC1.DAT ~/binsyn/oa/
#cp THLC2.DAT ~/binsyn/oa/
#cp OBSLC1.DAT ~/binsyn/oa/
#cp THLC3.DAT ~/binsyn/oa/
#cp OBSLC3.DAT ~/binsyn/oa/
#cp THLC4.DAT ~/binsyn/oa/
#cp OBSLC4.DAT ~/binsyn/oa/
#cp THLC5.DAT ~/binsyn/oa/
#cp OBSLC5.DAT ~/binsyn/oa/
