#!/bin/sh
# script to run LTCVA
set -e
cp ../ia/RFMG.DAT ./
cp ../ia/DPHS.DAT ./
cp ../ia/LTCVA.INF ./
cp ../oa/PGSX8.DAT ./
cp ../oa/LTCVA.DAT ./
cp ../oa/OBSLC1.DAT ./
cp ../oa/THLC1.DAT ./
cp ../oa/OBSLC2.DAT ./
cp ../oa/THLC2.DAT ./
cp ../oa/OBSLC2.DAT ./
cp ../oa/THLC3.DAT ./
cp ../oa/OBSLC4.DAT ./
cp ../oa/THLC4.DAT ./
cp ../oa/OBSLC5.DAT ./
cp ../oa/THLC5.DAT ./
./ltcva
cp THLC1.DAT ../oa/
cp OBSLC1.DAT ../oa/
set +e
#cp THLC2.DAT ../oa/
#cp OBSLC1.DAT ../oa/
#cp THLC3.DAT ../oa/
#cp OBSLC3.DAT ../oa/
#cp THLC4.DAT ../oa/
#cp OBSLC4.DAT ../oa/
#cp THLC5.DAT ../oa/
#cp OBSLC5.DAT ../oa/
cp THLC1.DAT ~/plotfiles/
cp OBSLC1.DAT ~/plotfiles/
#cp THLC2.DAT ~/plotfiles/
#cp OBSLC1.DAT ~/plotfiles/
#cp THLC3.DAT ~/plotfiles/
#cp OBSLC3.DAT ~/plotfiles/
#cp THLC4.DAT ~/plotfiles/
#cp OBSLC4.DAT ~/plotfiles/
#cp THLC5.DAT ~/plotfiles/
#cp OBSLC5.DAT ~/plotfiles/
